{
 "title": "Electricity",
 "description": "Data regarding electricity",
 "tags": [
  "power",
  "energy",
  "consumption"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "costsperkwh", "label": "€ / kWh", "query": "0.4354" }
  ]
 },
 "panels": [
  {
   "title": "Consumed power",
   "type": "stat",
   "description": "Total kWh consumed",
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mqtt_electricity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/consumedDeciWatt"
      }
     ]
    }
   ]
  },
  {
   "title": "Self produced breakdown",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "delivered to grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_electricity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/deliveredkwh"
      }
     ]
    },
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "Amortisation",
   "type": "bargauge",
   "description": "Add costs per kWh in query C directly, since no variables are allowed in expressions.",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A - $B)*0.4354", "type": "math" }
   ]
  },
  {
   "title": "Inverter status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "growatt",
     "select": [
      [
       { "params": [ "values_pvstatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "energy/growatt" }
     ]
    }
   ]
  },
  {
   "title": "Inverter temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "growatt",
     "select": [
      [
       { "params": [ "values_pvtemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "energy/growatt" }
     ]
    }
   ]
  },
  {
   "title": "Delivered power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Watt",
     "measurement": "mqtt_electricity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/deliveredkwh"
      }
     ]
    }
   ]
  },
  {
   "title": "Total produced power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "growatt",
     "select": [
      [
       { "params": [ "values_epvtotal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "energy/growatt" }
     ]
    }
   ]
  },
  {
   "title": "Balcony Ampere",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "growatt",
     "select": [
      [
       { "params": [ "values_pv1current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "energy/growatt" }
     ]
    }
   ]
  },
  {
   "title": "Meter uptime",
   "type": "stat",
   "description": "Uptime of smart meter",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_electricity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 86400" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/uptime"
      }
     ]
    }
   ]
  },
  {
   "title": "Inverter working time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "growatt",
     "select": [
      [
       { "params": [ "values_totworktime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 172800" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "energy/growatt" }
     ]
    }
   ]
  },
  {
   "title": "Balcony Volt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "growatt",
     "select": [
      [
       { "params": [ "values_pv1voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "energy/growatt" }
     ]
    }
   ]
  },
  {
   "title": "Consumption or delivery",
   "type": "timeseries",
   "description": "Current power consumption from or delivery to grid.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Watt Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_electricity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/currentWatt"
      }
     ]
    },
    {
     "alias": "Watt Inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "growatt",
     "select": [
      [
       { "params": [ "values_pvpowerout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "energy/growatt" }
     ]
    }
   ]
  },
  {
   "title": "Consumption and delivery last month",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT (last(\"value\")  / 10000 -first(\"value\") / 10000)*$costsperkwh FROM \"mqtt_electricity\" WHERE (\"topic\" = '/home/commodity/electricity/consumedDeciWatt') GROUP BY time(1d) fill(null) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/consumedDeciWatt"
      }
     ]
    },
    {
     "alias": "Consumed",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"value\")  / 10000 -first(\"value\") / 10000 FROM \"mqtt_electricity\" WHERE (\"topic\" = '/home/commodity/electricity/consumedDeciWatt') GROUP BY time(1d) fill(null) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/consumedDeciWatt"
      }
     ]
    },
    {
     "alias": "Delivered",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"value\")  / 10000 - first(\"value\") / 10000 FROM \"mqtt_electricity\" WHERE (\"topic\" = '/home/commodity/electricity/deliveredkwh') GROUP BY time(1d) fill(null) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/consumedDeciWatt"
      }
     ]
    }
   ]
  },
  {
   "title": "ESP Data",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "free heap",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_electricity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/freeheap"
      }
     ]
    },
    {
     "alias": "free block size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_electricity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/freeblocksize"
      }
     ]
    },
    {
     "alias": "fragmentation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_electricity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "/home/commodity/electricity/heapfragmentation"
      }
     ]
    }
   ]
  }
 ]
}